# -*- coding: utf-8 -*-
"""TharunAnand_ED20B068.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6xyHKlodKAKh1SoGjv1j644Wk76GrsD
"""

import cv2
from google.colab.patches import cv2_imshow

"""Question 1"""

import cv2
from matplotlib import pyplot as plt
img=cv2.imread('einstein.jpg')
plt.figure()
plt.imshow(img,cmap='gray'),plt.title("original"),plt.axis("off")
plt.show()

blur_gaus = cv2.GaussianBlur(img,(9,9),0,0)
blur_gaus1 = cv2.GaussianBlur(img,(5,5),0,0)
plt.figure(),plt.axis("off"),plt.title("Original Image"),plt.imshow(img,cmap='gray')
plt.figure(),plt.axis("off"),plt.title("Blurred Image"),plt.imshow(blur_gaus-blur_gaus1,cmap='gray')
plt.show()

"""Question 2"""

roi=cv2.imread('barel.jpg')
orig=cv2.imread('barels.jpg')
cv2_imshow(roi)
cv2_imshow(orig)

hsv_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
hsv_orig = cv2.cvtColor(orig, cv2.COLOR_BGR2HSV)

roi_hist=cv2.calcHist([hsv_roi],[0,1],None,[180,256],[0,180,0,256])
plt.imshow(roi_hist)
plt.show()

cv2.normalize(roi_hist,roi_hist,0,255,cv2.NORM_MINMAX)

res = cv2.calcBackProject([hsv_orig],[0,1],roi_hist,[0,180,0,256],1)

disc = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
cv2.filter2D(res,-1,disc)

ret,thresh = cv2.threshold(res,10,255,0)
thresh = cv2.merge((thresh,thresh,thresh))
fin = cv2.bitwise_and(orig,thresh)

cv2_imshow(fin)