# -*- coding: utf-8 -*-
"""Task-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v6WoJfVOT78AtqbmfKvz8O7Bl7HK2bhU
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

img=cv2.imread('/content/cv2/einstein[1].jpg')
blur_img1=cv2.GaussianBlur(img,(5,5),0,0)
blur_img2=cv2.GaussianBlur(img,(9,9),50,50)

plt.figure(),plt.axis("off"),plt.title("Blur5"),plt.imshow(blur_img1)
plt.figure(),plt.axis("off"),plt.title("Blur9"),plt.imshow(blur_img2)
plt.figure(),plt.axis("off"),plt.title("Edges"),plt.imshow(blur_img1-blur_img2)

