# -*- coding: utf-8 -*-
"""Question1_EE20B133.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13xbaibwVw3gNxyH71pD0JWbYVKe9YcaK

Answer 1:
"""

import cv2
from matplotlib import pyplot as plt

img=cv2.imread('/content/einstein.jpg',0)
blur1=cv2.GaussianBlur(img,(9,9),0)
blur2=cv2.GaussianBlur(img,(5,5),1)
plt.figure(),plt.imshow(img,cmap='gray'),plt.axis("off"),plt.title("OG Einstein")
plt.figure(),plt.imshow(blur1,cmap='gray'),plt.axis("off"),plt.title("Blurred Einstein1")
plt.figure(),plt.imshow(blur2,cmap='gray'),plt.axis("off"),plt.title("Blurred Einstein2")
diff=blur1.copy()
cv2.absdiff(blur1,blur2,diff)
plt.figure(),plt.imshow(diff,cmap='gray'),plt.axis("off"),plt.title("ans")